source "https://github.com/CocoaPods/Specs.git"

platform :ios, '8.3'
use_frameworks!

target 'TPSVG_Example' do
  pod 'TPSVG', :path => '../'

  target 'TPSVG_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
