source "https://github.com/CocoaPods/Specs.git"

platform :ios, "12.1"
use_frameworks!

target "TPSVG_Example" do
    pod "TPSVG", :path => "../"

    target "TPSVG_Tests" do
        inherit! :search_paths

        pod "Quick"
        pod "Nimble"
    end
end
