os: osx
osx_iamge: xcode10
cache:
- bundler
- cocoapods
env:
  global:
  - WORKSPACE=Example/TPSVG.xcworkspace
  - PROJECT=Example/TPSVG.xcodeproj
  - TEST_FRAMEWORK_SCHEME="TPSVG-Example"
  - EXAMPLE_SCHEME="TPSVG-Example"
  - SOURCE_FOLDER="Source"
  matrix:
  - DESTINATION="OS=11.3,name=iPhone 8"
install:
- bundle install
- bundle exec pod repo update
- bundle exec pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -list
- xcodebuild -workspace "$WORKSPACE" -scheme "$TEST_FRAMEWORK_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES build test | xcpretty
- xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk iphonesimulator
- destination "$DESTINATION" -configuration Debug -derivedDataPath ${TRAVIS_BUILD_DIR}/derived_data ONLY_ACTIVE_ARCH=YES build | xcpretty
- pod lib lint --allow-warnings
after_success:
- slather coverage -t --build-directory ${TRAVIS_BUILD_DIR}/derived_data --verbose
- bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode
